sudo: false
language: rust
rust:
- 1.27.0  # Oldest supported version
- stable
- beta
- nightly
matrix:
  include:
  - env: RUSTFMT
    rust: 1.29.1  # `stable`: Locking down for consistent behavior
    install:
      - rustup component add rustfmt-preview
    script:
      - cargo fmt -- --check
  - env: RUSTFLAGS="-D warnings"
    rust: 1.29.1  # `stable`: Locking down for consistent behavior
    install:
    script:
    - cargo check --tests
  - env: CLIPPY
    rust: nightly-2018-11-10
    install:
      - rustup component add clippy-preview
    script:
      - cargo clippy --all-features

install:
- rustc -Vv
- cargo -V
- export PATH=$HOME/.cargo/bin:$PATH

script:
- cargo check --verbose --all
- cargo test  --verbose --all

branches:
  only:
  # Release tags
  - /^v\d+\.\d+\.\d+.*$/
  - master

# Need to cache the whole `.cargo` directory to keep .crates.toml for
# cargo-update to work
cache:
  directories:
    - /home/travis/.cargo
# But don't cache the cargo registry
before_cache:
- rm -rf $HOME/.cargo/registry
# Travis can't cache files that are not readable by "others"
- chmod -R a+r $HOME/.cargo

notifications:
  email:
    on_success: never
